packages:
- .
extra-deps:
- path-0.5.2
- Win32-notify-0.3.0.1
- hfsevents-0.1.5
- project-template-0.2.0
- filelock-0.1.0.1
resolver: lts-2.17
image:
  container:
    base: "fpco/ubuntu-with-libgmp:14.04"
    add:
      man/: /usr/local/share/man/
    entrypoints:
      - stack
